### ISSUE TITLE
Sentinel-3 download interrupted

### ISSUE THREAD

**Issue by dilthomas** [DHI-GRAS/creodias-finder#5]
while downloading sentinel3 product, the download gets interrupted in between and am unable to download the product

**Comment by j08lue** [comment]
Can you please provide some details, ideally an [MWE](https://stackoverflow.com/help/minimal-reproducible-example), how to reproduce your problem?

**Comment by dilthomas** [comment]
The product file is of 530MB, but the download fails at 271MB

```python
result = query.query('Sentinel3',
                    start_date = datetime(2016,7,1),
                    end_date = datetime(2016,7,1),
                    geometry = footprint,
                    productType='RBT',
                    orbitDirection='descending')
ids = [key['id'] for key in result.values()]
download.download(ids[0],outfile='D:/RawData/',**credentials)
```

```
-------------------------------------
271MB [10:17, 439kB/s] 
Error: Destination path 'D:/RawData/.incomplete' already exists
```

**Comment by j08lue** [comment]
The error you posted `Destination path 'D:/RawData/.incomplete' already exists` is because we changed the API (without updating the example, sorry), such that it takes a complete file path, not just the folder. So when you make that `'D:/RawData/some-file.zip`, that message should go away. 

However, the original issue must have been a different one. Please delete any `.incomplete` files and try again. Maybe it was just a server glitch. If you get the same problem, please report.

Also note: this library is just a quick proof of concept. Great if you still can use it for something.

**Comment by dilthomas** [comment]
thanks @j08lue 

I have tried by giving file name also, but still its getting interrupted. I think it might be an issue in the server side, because i am facing the same issue while trying to download from their user interface.

**Comment by j08lue** [comment]
Thanks for the feedback. In that case, you will have to file a bug report with CreoDIAS. Please do keep us posted about their response.

**Comment by dilthomas** [comment]
Ok, sure.

**Comment by dilthomas** [comment]
@j08lue the download was failing in my system, but when i tried it in aws instance it was working fine. May be some issue with my network, have sent the tcpdump to the team on their request.

**Comment by j08lue** [comment]
Cool.
